# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(choices=[("SHIPMENT", "Shipment"), ("INVOICE", "Invoice"), ("UNCLASSIFIED", "Unclassified")], db_index=True, max_length=32)),
                ("entity_id", models.CharField(db_index=True, max_length=255)),
                ("canonical_status", models.CharField(db_index=True, max_length=64)),
                ("event_time", models.DateTimeField(db_index=True)),
                ("normalized_payload", models.JSONField()),
                ("confidence_score", models.FloatField()),
                ("llm_model", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "webhook",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="normalized_event", to="ingestion.rawwebhook"),
                ),
            ],
            options={"ordering": ["-event_time"]},
        ),
        migrations.AddIndex(
            model_name="normalizedevent",
            index=models.Index(fields=["entity_type", "entity_id", "event_time"], name="norm_entity_event_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedevent",
            index=models.Index(fields=["canonical_status", "created_at"], name="norm_status_created_idx"),
        ),
    ]
