# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("normalization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.CharField(max_length=255)),
                ("latest_status", models.CharField(max_length=64)),
                ("latest_event_time", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latest_event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="state_snapshots", to="normalization.normalizedevent"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="entitystate",
            constraint=models.UniqueConstraint(fields=("entity_type", "entity_id"), name="uq_entity_type_id"),
        ),
        migrations.AddIndex(
            model_name="entitystate",
            index=models.Index(fields=["entity_type", "entity_id"], name="entity_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="entitystate",
            index=models.Index(fields=["latest_event_time"], name="entity_latest_time_idx"),
        ),
    ]
