# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawWebhook",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vendor", models.CharField(db_index=True, max_length=128)),
                ("external_event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSING", "Processing"),
                            ("NORMALIZED", "Normalized"),
                            ("FAILED", "Failed"),
                            ("DEAD_LETTER", "Dead Letter"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=32,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.AddIndex(
            model_name="rawwebhook",
            index=models.Index(fields=["vendor", "received_at"], name="raw_vendor_received_idx"),
        ),
        migrations.AddIndex(
            model_name="rawwebhook",
            index=models.Index(fields=["external_event_id"], name="raw_ext_event_idx"),
        ),
        migrations.AddIndex(
            model_name="rawwebhook",
            index=models.Index(fields=["processing_status", "received_at"], name="raw_status_received_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawwebhook",
            constraint=models.UniqueConstraint(
                fields=("vendor", "idempotency_key"), name="uq_vendor_idempotency_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawwebhook",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_event_id__isnull", False)),
                fields=("vendor", "external_event_id"),
                name="uq_vendor_external_event",
            ),
        ),
    ]
